# Generated by Django 2.2.2 on 2019-06-25 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('login', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('profile_image_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('duration', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=40)),
                ('thumb_nail_url', models.CharField(max_length=300)),
                ('streamer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Streamer')),
            ],
        ),
    ]
