# Generated by Django 2.2.2 on 2019-06-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.IntegerField()),
                ('streamer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Streamer')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Video')),
            ],
        ),
    ]
